---
title: "HW6 Telemarketing"
author: "Enter Your Name Here"
date: "3/22/2020"
output:
  html_document:
    toc: true
    theme: readable
    highlight: tango
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Downloading and Prepping the Data

```{r}
#Downloading and Prepping the Data
tele <- read.csv("tele.csv", stringsAsFactors = TRUE)
summary(tele)

#We are deleting the "duration" variable because it is an after the fact measurement. We only should be using variables that we know before the call
tele$duration <- NULL

# Deleting the column X
tele$X <- NULL

# Changing pdays to a dummy and deleting pdays
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL

str(tele)
```

## Getting Data Ready for Analysis

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

telemm <- as.data.frame(model.matrix(~.-1,tele))
str(telemm)

# Randomize the rows in the data (shuffling the rows)
set.seed(12345)
tele_random <- telemm[sample(nrow(telemm)),]

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything 
tele_norm <- as.data.frame(lapply(telemm, normalize))
```


## Getting Train and Test Samples

```{r}
# Selects 10000 random rows for test data
set.seed(12345)
test_set <- sample(1:nrow(tele_norm), 10000) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 

# Create a train set and test set
#First the predictors - all columns except the yyes column
tele_train <- tele_norm[-test_set, -match("yyes",names(tele_norm))]
tele_test <- tele_norm[test_set, -match("yyes",names(tele_norm))]

#Now the response (aka Labels) - only the yyes column
tele_train_labels <- tele_norm[-test_set, "yyes"]
tele_test_labels <- tele_norm[test_set, "yyes"]

```

> Now you are ready to build your ANN model. Feel free to modify the data load, cleaning and preparation code above as per your preference.

```{r}
tele_norm$yyes <- NULL
tele_norm_cluster <- kmeans(tele_norm, 5)

tele_norm_cluster$size
tele_norm_cluster$centers

tele_norm$cluster <- tele_norm_cluster$cluster
str(tele_norm)

tele_norm$yyes <- telemm$yyes

aggregate(data = tele_norm, yyes ~ cluster, mean)

```

## Cluster 1

```{r}
library(dplyr)
Cluster1_Logistic <- tele_norm %>%
filter(cluster==1)

Cluster1_Logistic_Model <- glm(yyes ~ age + jobadmin. + jobblue.collar + maritalmarried + maritalsingle + educationbasic.9y + educationhigh.school + educationuniversity.degree + defaultunknown + housingyes + monthjun + monthmay + day_of_weekmon + day_of_weekthu + day_of_weektue + day_of_weekwed, data = Cluster1_Logistic, family = "binomial")
summary(Cluster1_Logistic_Model)

library(gmodels)
library(caret)
library(class)

Predict_Cluster1 <- predict(Cluster1_Logistic_Model, newdata = Cluster1_Logistic)
Predict_Cluster1 <- ifelse(Predict_Cluster1 > .5, 1, 0)

CrossTable(x = Cluster1_Logistic_Model$y, y = Predict_Cluster1, 
           prop.chisq=FALSE)

Cluster1_Table <- table(Cluster1_Logistic_Model$y, Predict_Cluster1)
CrossTable(Cluster1_Table)

# KNN Model
test_size_1 = round(nrow(Cluster1_Logistic)*0.8)
cluster1_test_set <- sample(1:nrow(Cluster1_Logistic), test_size_1) 
cluster1_train <- Cluster1_Logistic[-cluster1_test_set, -match("yyes",names(Cluster1_Logistic))]
cluster1_test <- Cluster1_Logistic[cluster1_test_set, -match("yyes",names(Cluster1_Logistic))]
k_val <- round(sqrt(nrow(cluster1_train)))
#Now the response (aka Labels) - only the yyes column
cluster1_train_labels <- Cluster1_Logistic[-cluster1_test_set, "yyes"]
cluster1_test_labels <- Cluster1_Logistic[cluster1_test_set, "yyes"]
cluster1_train_labels <- as.factor(cluster1_train_labels)
cluster1_test_labels <- as.factor(cluster1_test_labels)

Cluster1_test_pred <- knn(train = cluster1_train, test = cluster1_test,
                      cl = cluster1_train_labels, k=k_val)

#Evaluate model results
CrossTable(x = cluster1_test_labels, y = Cluster1_test_pred, 
           prop.chisq=FALSE)

# example using the caret package
# calculates everything for you
confusionMatrix(Cluster1_test_pred, cluster1_test_labels, positive = "1")
```

## Cluster 2

```{r}
library(dplyr)
Cluster2_Logistic <- tele_norm %>%
filter(cluster==2)

Cluster2_Logistic_Model <- glm(yyes ~ age + jobadmin. + jobblue.collar + maritalmarried + educationbasic.9y + educationhigh.school + educationuniversity.degree + defaultunknown + housingyes + monthmay + day_of_weekmon + day_of_weekthu + day_of_weektue + day_of_weekwed, data = Cluster2_Logistic, family = "binomial")
summary(Cluster2_Logistic_Model)

library(gmodels)
library(caret)
library(class)


# KNN Model
test_size_2 = round(nrow(Cluster2_Logistic)*0.8)
cluster2_test_set <- sample(1:nrow(Cluster2_Logistic), test_size_2) 
cluster2_train <- Cluster2_Logistic[-cluster2_test_set, -match("yyes",names(Cluster2_Logistic))]
cluster2_test <- Cluster2_Logistic[cluster2_test_set, -match("yyes",names(Cluster2_Logistic))]
k_val <- round(sqrt(nrow(cluster2_train)))
#Now the response (aka Labels) - only the yyes column
cluster2_train_labels <- Cluster2_Logistic[-cluster2_test_set, "yyes"]
cluster2_test_labels <- Cluster2_Logistic[cluster2_test_set, "yyes"]
cluster2_train_labels <- as.factor(cluster2_train_labels)
cluster2_test_labels <- as.factor(cluster2_test_labels)

Cluster2_test_pred <- knn(train = cluster2_train, test = cluster2_test,
                      cl = cluster2_train_labels, k=k_val)

#Evaluate model results
CrossTable(x = cluster2_test_labels, y = Cluster2_test_pred, 
           prop.chisq=FALSE)

# example using the caret package
# calculates everything for you
confusionMatrix(Cluster2_test_pred, cluster2_test_labels, positive = "1")
```


## Cluster 4

```{r}
library(dplyr)
Cluster4_Logistic <- tele_norm %>%
filter(cluster==4)

Cluster4_Logistic_Model <- glm(yyes ~ age + jobadmin. + jobblue.collar + jobtechnician +  maritalmarried + maritalsingle + educationhigh.school + educationuniversity.degree + defaultunknown + housingyes + monthaug + monthjul + day_of_weekmon + day_of_weekthu + day_of_weektue + day_of_weekwed, data = Cluster4_Logistic, family = "binomial")
summary(Cluster4_Logistic_Model)

library(gmodels)
library(caret)
library(class)


# KNN Model
test_size_4 = round(nrow(Cluster4_Logistic)*0.8)
cluster4_test_set <- sample(1:nrow(Cluster4_Logistic), test_size_4) 
cluster4_train <- Cluster4_Logistic[-cluster4_test_set, -match("yyes",names(Cluster4_Logistic))]
cluster4_test <- Cluster4_Logistic[cluster4_test_set, -match("yyes",names(Cluster4_Logistic))]
k_val <- round(sqrt(nrow(cluster4_train)))
#Now the response (aka Labels) - only the yyes column
cluster4_train_labels <- Cluster4_Logistic[-cluster4_test_set, "yyes"]
cluster4_test_labels <- Cluster2_Logistic[cluster4_test_set, "yyes"]
cluster4_train_labels <- as.factor(cluster4_train_labels)
cluster4_test_labels <- as.factor(cluster4_test_labels)

Cluster4_test_pred <- knn(train = cluster4_train, test = cluster4_test,
                      cl = cluster4_train_labels, k=k_val)

#Evaluate model results
CrossTable(x = cluster4_test_labels, y = Cluster4_test_pred, 
           prop.chisq=FALSE)

# example using the caret package
# calculates everything for you
confusionMatrix(Cluster4_test_pred, cluster4_test_labels, positive = "1")
```


