---
title: "ANN_tele"
author: "Young-Bin Kim"
date: "2022-10-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Downloading and Prepping the Data
tele <- read.csv("tele.csv", stringsAsFactors = TRUE)
summary(tele)

#We are deleting the "duration" variable because it is an after the fact measurement. We only should be using variables that we know before the call
tele$duration <- NULL

# Deleting the column X
tele$X <- NULL

# Changing pdays to a dummy and deleting pdays
tele$pdaysdummy <- ifelse(tele$pdays == 999, 0, 1)
tele$pdays <- NULL

str(tele)
```

## Getting Data Ready for Analysis

```{r}
# Using model.matrix to convert all the factors to dummy variables
# We are converting all of the factors into dummy variables as the input into knn has to be numeric

telemm <- as.data.frame(model.matrix(~.-1,tele))
str(telemm)

# Randomize the rows in the data (shuffling the rows)
set.seed(12345)
tele_random <- telemm[sample(nrow(telemm)),]

#Normalize the data
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}

# we are going to normalize everything 
tele_norm <- as.data.frame(lapply(telemm, normalize))
```


## Getting Train and Test Samples

```{r}
# Selects 10000 random rows for test data
#set.seed(12345)
#test_set <- sample(1:nrow(tele_norm), 10000) 
# Depending on R-version and computer, different rows may be selected. 
# If that happens, results are different. 

# Create a train set and test set
#First the predictors - all columns except the yyes column
#tele_train <- tele_norm[-test_set, -match("yyes",names(tele_norm))]
#tele_test <- tele_norm[test_set, -match("yyes",names(tele_norm))]

#Now the response (aka Labels) - only the yyes column
#tele_train_labels <- tele_norm[-test_set, "yyes"]
#tele_test_labels <- tele_norm[test_set, "yyes"]

```

> Now you are ready to build your ANN model. Feel free to modify the data load, cleaning and preparation code above as per your preference.

```{r}
tele_norm$yyes <- NULL
tele_norm_cluster <- kmeans(tele_norm, 5)

tele_norm_cluster$size
tele_norm_cluster$centers

tele_norm$cluster <- tele_norm_cluster$cluster
str(tele_norm)

tele_norm$yyes <- telemm$yyes

aggregate(data = tele_norm, yyes ~ cluster, mean)

```


# ANN Model

## Cluster 2
```{r, cache=TRUE}
library(dplyr)

head(tele_norm)

cluster2 <- tele_norm %>% filter(cluster == 2)

str(cluster2)

cluster2_train <- cluster2[1:2800,]
cluster2_test <- cluster2[2800:3693,]

summary(cluster2_train)
library(neuralnet)

cluster2model <- neuralnet(formula = yyes ~., data = cluster2_train, hidden = c(6,3), stepmax = 1000000, threshold = 0.1)
plot(cluster2model)

```

## Cluster 3
```{r, cache=TRUE}
cluster3 <- tele_norm %>% filter(cluster == 3)

cluster3_train <- cluster3[1:6200, ]
cluster3_test <- cluster3[6200:8186, ]

summary(cluster3_train)

cluster3model <- neuralnet(formula = yyes ~., data = cluster3_train, hidden = c(6,3), stepmax = 1000000, threshold = 0.1)
plot(cluster3model)
```
## Cluster 4
```{r, cache=TRUE}
cluster4 <- tele_norm %>% filter(cluster == 4)
str(cluster4)
                                 
cluster4_train <- cluster4[1:4600, ]
cluster4_test <- cluster4[4600:6302, ]

summary(cluster4_train)

cluster4model <- neuralnet(formula = yyes ~., data = cluster4_train, hidden = c(6,3), stepmax = 1000000, threshold = 0.1)
plot(cluster4model)
```
## Cluster 5
```{r, cache=TRUE}
cluster5 <- tele_norm %>% filter(cluster == 5)
str(cluster5)
                                 
cluster5_train <- cluster5[1:7400, ]
cluster5_test <- cluster5[7400:9873, ]

summary(cluster5_train)

cluster5model <- neuralnet(formula = yyes ~., data = cluster5_train, hidden = c(6,3), stepmax = 1000000, threshold = 0.1)
plot(cluster5model)
```

# Results
```{r}
results_cluster2 <- compute(cluster2model, cluster2_test[-yyes])

predicted_yes2 <- results_cluster2$net.result

```




